Adds support for docker with each example app
recurly/recurly-integration-examples pull request #72
Opened 2020-09-22 18:33 UTC by dbrudner

Just a couple notes:

- Because the `public` directory is at the root of the repo, the build context for each of the examples needed to be set there.
- To preserve the capability to run the examples locally, I added an environment variable `PUBLIC_DIR_PATH` to some of the examples to specify where the static directory should be served from. Because this value is slightly different in some of the examples and php doesn't need it, that value is specified in the example app's `docker-compose.yml` files

2020-09-22 18:51 UTC, chrissrogers requested changes

2020-09-22 18:51 UTC, chrissrogers commented on api/java/Dockerfile
> +COPY ./public ./src/main/resources/public
Might be good to add a comment here to explain the directory placement

2020-09-22 18:51 UTC, chrissrogers commented on api/php/Dockerfile
> +RUN curl -sS https://getcomposer.org/installer | php
Thoughts on using https://hub.docker.com/_/composer ?

2020-09-22 18:51 UTC, chrissrogers commented on api/ruby/Dockerfile
> +FROM ruby:2.5
Let's go with `2` or `latest`

2020-09-22 18:51 UTC, chrissrogers commented on api/ruby/app.rb
> +set :bind, '0.0.0.0'
Will this still work for local execution?

2020-09-22 18:51 UTC, chrissrogers commented on docker.env
> +ERROR_URL=
Beautiful

2020-09-22 20:20 UTC, douglasmiller commented on api/ruby/app.rb
> +set :bind, '0.0.0.0'
Yes, `0.0.0.0` means bind to all available network interfaces

2020-09-23 14:15 UTC, dbrudner commented on api/java/Dockerfile
> +COPY ./public ./src/main/resources/public
https://github.com/recurly/recurly-integration-examples/pull/72/commits/7138f4e9f1a818515653414fee57de5a0d3d62d5

2020-09-23 14:15 UTC, dbrudner commented on api/php/Dockerfile
> +RUN curl -sS https://getcomposer.org/installer | php
https://github.com/recurly/recurly-integration-examples/pull/72/commits/ad30d3e9a0f6b06524a0c97d0718d4aeeb1514dd

2020-09-23 14:15 UTC, dbrudner commented on api/ruby/Dockerfile
> +FROM ruby:2.5
https://github.com/recurly/recurly-integration-examples/pull/72/commits/e4de5248225012d725bd1ad441b7cb08dd95ba91

2020-09-23 14:15 UTC, dbrudner commented on docker.env
> +ERROR_URL=
yeet

2020-09-23 18:39 UTC, chrissrogers requested changes

2020-09-23 18:39 UTC, chrissrogers commented on api/php/Dockerfile
> +RUN php composer.phar install
Since composer has not been installed locally to the workdir but is available globally, I think this command will need to be `composer install`

2020-09-23 21:35 UTC, douglasmiller commented
Should we include `volume` mounts in the docker-compose files for local development/usage? These docker images are trivial to build, but it's still frustrating

2020-09-28 16:19 UTC, dbrudner commented on api/java/src/main/java/com/recurly/App.java
> +      staticFiles.externalLocation(publicDir);
This is mostly derived from http://sparkjava.com/documentation#examples-and-faq under the heading "How do I enable automatic refresh of static files?"

2020-09-29 17:33 UTC, chrissrogers approved these changes

2020-09-29 17:33 UTC, merged