Elements rebase
recurly/recurly-integration-examples pull request #76
Opened 2020-09-24 21:24 UTC by dbrudner

2020-09-29 16:58 UTC, douglasmiller commented
The card input fields are not styled correctly on the 3D Secure page

2020-09-29 22:01 UTC, joannasese approved these changes

2020-09-30 14:52 UTC, chrissrogers requested changes

2020-09-30 14:52 UTC, chrissrogers commented on public/advanced-pricing-items/index.html
> +      <form method="post" action="/api/subscriptions/new">
This will need to remain `purchases` for now since this form is shaped to fulfill that endpoint's form expectations.

`/api/purchases/new` only exists on the ruby example, but future work will consolidate each backend example app onto `/api/purchases/new`.

2020-09-30 17:36 UTC, dbrudner commented
> The card input fields are not styled correctly on the 3D Secure page

I think this is a caching issue. Can you try opening the page in an incognito window?

2020-09-30 17:43 UTC, dbrudner commented on public/advanced-pricing-items/index.html
> +      <form method="post" action="/api/subscriptions/new">
https://github.com/recurly/recurly-integration-examples/pull/76/commits/02a45f391432445bccd81144929f9b4c2156ccc7

2020-10-01 01:52 UTC, chrissrogers approved these changes

2020-10-01 01:52 UTC, merged